# -*- coding: utf-8 -*-
"""nifty-50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-wjBxYk9v3LIiLOmf2ckSv2qT7GJtBDd
"""

import numpy as np
import pandas as pd 
import os
for dirname, _, filenames in os.walk('/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
const dt = pd.read_csv('/National_Stock_Exchange_of_India_Ltd.csv');

dt.head()

nifty_50.shape

nifty_50.head(10)

new=nifty_50.sort_values('365 d % chng',ascending = False).head(10)
new[['Symbol','365 d % chng']]

top_losers_year=nifty_50[nifty_50['365 d % chng']<0]
df=top_losers_year.sort_values('365 d % chng')
df[['Symbol','365 d % chng']]

nifty_50.sort_values('30 d % chng',ascending = False).head(10)

nifty_50.sort_values('% Chng',ascending = False).head(10)

nifty_50.sort_values('Volume (lacs)',ascending = False).head(10)